[project]
name = "pytfredon-hw"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.1",
    "psutil>=7.0.0",
    "pyamdgpuinfo>=2.1.7",
    "pynvml>=12.0.0",
    "pyside6>=6.9.1",
    "pytest>=8.4.1",
]
